=== IrenaKozlovskaya/Projects_FreeIT/Project/booksXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="books">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="book" type="book" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="book">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="ISBN" type="xsd:string"/>
            <xsd:element name="author" type="author"/>
            <xsd:element name="genre" type="genre"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="author">
        <xsd:sequence>
            <xsd:element name="authorName" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="genre">
        <xsd:sequence>
            <xsd:element name="name" type="genreName"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="genreName">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="роман"/>
            <xsd:enumeration value="проза"/>
            <xsd:enumeration value="искусствоведение"/>
            <xsd:enumeration value="повесть"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== IrenaKozlovskaya/Projects_FreeIT/Project/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="booksXSD.xsd">
    <book>
        <title>Убить пересмешника</title>
        <ISBN>213236565</ISBN>
        <author>
            <authorName>Харпер Ли</authorName>
        </author>
        <genre>
            <name>роман</name>
        </genre>
    </book>
    <book>
        <title>Пойди поставь сторожа</title>
        <ISBN>435435454</ISBN>
        <author>
            <authorName>Харпер Ли</authorName>
        </author>
        <genre>
            <name>проза</name>
        </genre>
    </book>
    <book>
        <title>Старик и море</title>
        <ISBN>21351654465</ISBN>
        <author>
            <authorName>Хэмингуэй</authorName>
        </author>
        <genre>
            <name>повесть</name>
        </genre>
    </book>
    <book>
        <title>Апокалипсис в искусстве</title>
        <ISBN>435458484</ISBN>
        <author>
            <authorName>Софья Багдасарова</authorName>
        </author>
        <genre>
            <name>искусствоведение</name>
        </genre>
    </book>
    <book>
        <title>По ком звонит колокол</title>
        <ISBN>35435435</ISBN>
        <author>
            <authorName>Хэмингуэй</authorName>
        </author>
        <genre>
            <name>роман</name>
        </genre>
    </book>
</books>
